module.exports = {
    // 🌟 Superadmin
    CREATE_USER: "CREATE_USER",
    VIEW_USER: "VIEW_USER",
    VIEW_USER_BY_ID: "VIEW_USER_BY_ID",
    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_BY_ID: "UPDATE_USER_BY_ID",
    DELETE_USER: "DELETE_USER",
    DELETE_USER_BY_ID: "DELETE_USER_BY_ID",
    VIEW_ADMIN_ACTIVITY: "VIEW_ADMIN_ACTIVITY",

    // 🛠️ Admin Dev
    CREATE_BOOK: "CREATE_BOOK",
    VIEW_BOOK: "VIEW_BOOK",
    VIEW_BOOK_BY_ID: "VIEW_BOOK_BY_ID",
    UPDATE_BOOK: "UPDATE_BOOK",
    UPDATE_BOOK_BY_ID: "UPDATE_BOOK_BY_ID",
    DELETE_BOOK: "DELETE_BOOK",
    DELETE_BOOK_BY_ID: "DELETE_BOOK_BY_ID",

    CREATE_CATEGORY: "CREATE_CATEGORY",
    VIEW_CATEGORY: "VIEW_CATEGORY",
    VIEW_CATEGORY_BY_ID: "VIEW_CATEGORY_BY_ID",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",
    UPDATE_CATEGORY_BY_ID: "UPDATE_CATEGORY_BY_ID",
    DELETE_CATEGORY: "DELETE_CATEGORY",
    DELETE_CATEGORY_BY_ID: "DELETE_CATEGORY_BY_ID",

    CREATE_BLOG: "CREATE_BLOG",
    VIEW_BLOG: "VIEW_BLOG",
    VIEW_BLOG_BY_ID: "VIEW_BLOG_BY_ID",
    UPDATE_BLOG: "UPDATE_BLOG",
    UPDATE_BLOG_BY_ID: "UPDATE_BLOG_BY_ID",
    DELETE_BLOG: "DELETE_BLOG",
    DELETE_BLOG_BY_ID: "DELETE_BLOG_BY_ID",

    // 📦 Admin Business
    CREATE_DISCOUNT: "CREATE_DISCOUNT",
    VIEW_DISCOUNT: "VIEW_DISCOUNT",
    VIEW_DISCOUNT_BY_ID: "VIEW_DISCOUNT_BY_ID",
    UPDATE_DISCOUNT: "UPDATE_DISCOUNT",
    UPDATE_DISCOUNT_BY_ID: "UPDATE_DISCOUNT_BY_ID",
    DELETE_DISCOUNT: "DELETE_DISCOUNT",
    DELETE_DISCOUNT_BY_ID: "DELETE_DISCOUNT_BY_ID",

    CREATE_ORDER: "CREATE_ORDER",
    VIEW_ORDER: "VIEW_ORDER",
    VIEW_ORDER_BY_ID: "VIEW_ORDER_BY_ID",
    UPDATE_ORDER: "UPDATE_ORDER",
    UPDATE_ORDER_BY_ID: "UPDATE_ORDER_BY_ID",
    DELETE_ORDER: "DELETE_ORDER",
    DELETE_ORDER_BY_ID: "DELETE_ORDER_BY_ID",

    VIEW_SALES_REPORT: "VIEW_SALES_REPORT"
};
